# Generated by Django 3.0.8 on 2020-07-20 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('provincia', models.CharField(choices=[('Maputo Provincia ', 'Maputo Provincia'), ('Maputo Cidade', 'Maputo Cidade'), ('Gaza', 'Gaza'), ('Inhambane', 'Inhambane'), ('Sofala', 'Sofala'), ('Manica', 'Manica'), ('Tete', 'Tete'), ('Zambezia', 'Zambezia'), ('Nampula', 'Nampula'), ('Cabo Delgado', 'Cabo Delgado'), ('Niassa', 'Niassa')], max_length=30)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reuniao', models.DateField(default=django.utils.timezone.now)),
                ('familia', models.CharField(max_length=100)),
                ('membros', models.IntegerField()),
                ('bairro', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=50)),
                ('reuniao', models.CharField(choices=[('Sexta-Feira', 'Sexta-Feira'), ('Domingo', 'Domingo')], max_length=20)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Plataforma')),
            ],
        ),
    ]
